"""Fast utility scanner, utilities_cache.json compiler and SHA-256 auto-validation.

Design
------
* ``scan_and_cache`` walks ``utilities/`` once, validates each utility's
  ``manifest.json`` / ``form_schema.json``, hashes every runtime file with
  SHA-256, syncs each utility's ``assets/icons`` into the frontend icon base,
  and persists a compiled ``utilities_cache.json`` in the utilities root.
* On application startup ``load_utilities`` prefers the cache: it recomputes the
  SHA-256 digests of the manifest/schema/runtime files and compares them with
  the stored hashes. Matching entries boot instantly (Fast Boot); a changed
  utility is re-parsed, re-cached, and recorded in ``util_lists_cache-lock.json``.
* The utilities root deliberately holds only utility folders plus the two JSON
  caches, so listing it is a cheap way for the dashboard to stay responsive.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import sys

from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

CACHE_VERSION = 1

_MOD_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Standalone runs (`python core/scanner.py`) must resolve the top-level
# `core` package; when imported by main.py the project root is already on the
# path and this insert is a harmless no-op.
if _MOD_ROOT not in sys.path:
    sys.path.insert(0, _MOD_ROOT)

from core.schema import validate_manifest, validate_form_schema


def _resolve(*parts: str) -> str:
    return os.path.join(_MOD_ROOT, *parts)


UTILITIES_DIR = os.environ.get("LYCAN_UTILITIES_DIR") or _resolve("utilities")
CACHE_PATH = _resolve("utilities", "utilities_cache.json")
LOCK_PATH = _resolve("utilities", "util_lists_cache-lock.json")
# Generated icon mirrors live in the tracked-free public cache so utility icons
# are still web-servable without polluting the repo with autogenerated PNGs.
ICON_TARGET_DIR = _resolve("frontend", "public", "assets", ".cache", "icons")
ICON_BASE = "assets/.cache/icons"


def sha256_file(path: str) -> Optional[str]:
    """SHA-256 hex digest of a file, or None when unreadable."""
    try:
        h = hashlib.sha256()
        with open(path, "rb") as fh:
            for chunk in iter(lambda: fh.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()
    except OSError:
        return None


def _sync_icons(module_dir: str, icon_file: Optional[str]) -> Optional[str]:
    """Copy a utility's ``assets/icons`` into the frontend icon base.

    Returns the cache ``icon_rel`` (web-relative path) or None when the utility
    ships no icons. Every PNG under ``assets/icons`` is mirrored, so a utility
    may expose any number of icon variants.
    """
    chosen: Optional[str] = None
    icons_dir = os.path.join(module_dir, "assets", "icons")
    if os.path.isdir(icons_dir):
        try:
            os.makedirs(ICON_TARGET_DIR, exist_ok=True)
        except OSError:
            icons_dir = None
    if icons_dir and os.path.isdir(icons_dir):
        for fname in sorted(os.listdir(icons_dir)):
            src = os.path.join(icons_dir, fname)
            if not os.path.isfile(src):
                continue
            target = os.path.join(ICON_TARGET_DIR, fname)
            try:
                if not os.path.exists(target) or sha256_file(src) != sha256_file(target):
                    shutil.copy2(src, target)
            except OSError:
                continue
            if chosen is None and fname.lower().endswith((".png", ".jpg", ".jpeg", ".webp", ".gif")):
                chosen = ICON_BASE + "/" + fname
    if chosen is None and icon_file and str(icon_file).startswith(ICON_BASE + "/"):
        if os.path.isfile(os.path.join(module_dir, str(icon_file))):
            chosen = ICON_BASE + "/" + os.path.basename(str(icon_file))
    return chosen


def _file_hashes(module_dir: str, names: List[str]) -> Dict[str, str]:
    hashes: Dict[str, str] = {}
    for name in names:
        digest = sha256_file(os.path.join(module_dir, name))
        if digest:
            hashes[name] = digest
    return hashes


def _read_json(path: str):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def _json_error_detail(path: str, exc: ValueError) -> str:
    """Human-friendly, multi-line JSON parse diagnostic.

    Includes the parser's own message plus a caret frame showing the exact
    failing line/column so users can fix the JSON without guessing.
    """
    if not isinstance(exc, json.JSONDecodeError):
        return f"invalid JSON: {exc}"
    lineno, colno, pos = exc.lineno, exc.colno, exc.pos
    doc = exc.doc or ""
    lines = doc.splitlines()
    try:
        rel = os.path.relpath(path, UTILITIES_DIR)
    except ValueError:
        rel = os.path.basename(path)
    guide = f"{rel}: {exc.msg} (line {lineno}, column {colno}, char {pos})"
    if not lines:
        return guide
    caret = " " * max(colno - 1, 0) + "^"
    width = len(str(len(lines)))
    frame: List[str] = []
    for i in range(len(lines)):
        row = i + 1
        if abs(row - lineno) > 2:
            continue
        frame.append(f"  {row:>{width}} | {lines[i]}")
        if row == lineno:
            frame.append(f"  {' ' * width}   {caret}")
    return guide + "\n" + "\n".join(frame)


def _read_json_raw(path: str):
    """Like ``_read_json`` but keeps the exact parse diagnostics.

    Returns ``(data, error)`` where ``error`` is ``None`` or a dict with:
    * ``message`` - a multi-line human diagnostic (incl. a caret frame),
    * ``line``    - the failing 1-based line number, when the parser has one
    (used to point the load-error view's snippet at the offending location).
    """
    data = None
    error = None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
    except OSError as exc:
        error = {"message": f"could not read file: {exc}", "line": None}
    except ValueError as exc:
        error = {
            "message": _json_error_detail(path, exc),
            "line": exc.lineno if isinstance(exc, json.JSONDecodeError) else None,
        }
    return data, error


def _file_snippet(path: str, count: int = 5, anchor: Optional[int] = None) -> List[Tuple[int, str]]:
    """Lines of a file for the load-error view, as ``(line_number, text)``.

    Without ``anchor`` returns the last ``count`` non-empty lines. With an
    ``anchor`` line number the snippet is a ``count``-line window centered on
    that row, so the UI highlights the exact location of a parse error.
    """
    if not path or not os.path.isfile(path):
        return []
    lines: List[Tuple[int, str]] = []
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            for lineno, raw in enumerate(fh, 1):
                stripped = raw.rstrip("\r\n")
                lines.append((lineno, stripped))
    except OSError:
        return []
    if anchor is not None:
        start = max(anchor - count // 2, 1)
        return [(no, text) for no, text in lines if start <= no < start + count]
    return [(no, text) for no, text in lines if text.strip()][-count:]


def _module_error(module_dir: str) -> Optional[Dict[str, Any]]:
    """Describe why a utility folder failed to load (or None when not a utility).

    Produces the payload the UI's load-error tab renders: the offending file,
    the scanner/parser error messages and a source window around the failing
    line (or the last five lines when no exact location is known).
    """
    manifest_path = os.path.join(module_dir, "manifest.json")
    if not os.path.isfile(manifest_path):
        return None
    errors: List[str] = []
    mid = os.path.basename(module_dir.rstrip(os.sep)) or module_dir
    title = mid
    source = manifest_path
    manifest, parse_error = _read_json_raw(manifest_path)
    snippet_anchor: Optional[int] = None
    if parse_error:
        errors.append(parse_error["message"])
        if parse_error.get("line"):
            snippet_anchor = parse_error["line"]
    if not isinstance(manifest, dict):
        if not errors:
            errors.append(f"{os.path.relpath(manifest_path, UTILITIES_DIR)}: manifest must be a JSON object")
        if isinstance(manifest, dict):
            pass
        snippet_pairs = _file_snippet(manifest_path, anchor=snippet_anchor)
        return {
            "dir": os.path.normpath(module_dir),
            "id": str(mid),
            "title": str(title),
            "errors": errors,
            "source": source,
            "snippet": [text for _, text in snippet_pairs],
            "snippet_lines": [lineno for lineno, _ in snippet_pairs],
        }
    id_value = manifest.get("id")
    if isinstance(id_value, str) and id_value:
        mid = id_value
    title = str(manifest.get("title") or mid)
    errors.extend(validate_manifest(manifest))

    schema_name = manifest.get("schema") or "form_schema.json"
    schema_path = os.path.join(module_dir, schema_name)
    if os.path.isfile(schema_path):
        schema_data, schema_error = _read_json_raw(schema_path)
        source = schema_path
        if schema_error:
            errors.append(schema_error["message"])
            if schema_error.get("line"):
                snippet_anchor = schema_error["line"]
        else:
            schema_errors = validate_form_schema(schema_data)
            if schema_errors:
                source = schema_path
                errors.extend(schema_errors)

    runtime_name = str(manifest.get("runtime") or "") or None
    if runtime_name:
        runtime_path = os.path.join(module_dir, runtime_name)
        if not os.path.isfile(runtime_path) and not os.path.isfile(os.path.join(module_dir, runtime_name + ".py")):
            errors.append(f"runtime file '{runtime_name}' is missing")

    if not errors:
        return None
    snippet_pairs = _file_snippet(source, anchor=snippet_anchor)
    return {
        "dir": os.path.normpath(module_dir),
        "id": str(mid),
        "title": str(title),
        "errors": errors,
        "source": source,
        "snippet": [text for _, text in snippet_pairs],
        "snippet_lines": [lineno for lineno, _ in snippet_pairs],
    }


def collect_broken() -> Dict[str, Dict[str, Any]]:
    """Scan utilities/ for folders that look like utilities but failed loading."""
    broken: Dict[str, Dict[str, Any]] = {}
    if not os.path.isdir(UTILITIES_DIR):
        return broken
    for name in sorted(os.listdir(UTILITIES_DIR)):
        module_dir = os.path.join(UTILITIES_DIR, name)
        if not os.path.isdir(module_dir):
            continue
        error_entry = _module_error(module_dir)
        if error_entry:
            broken[error_entry["id"]] = error_entry
    return broken


def scan_utility(module_dir: str) -> Optional[Dict[str, Any]]:
    """Parse and validate one utility directory; None when invalid or absent."""
    manifest_path = os.path.join(module_dir, "manifest.json")
    if not os.path.isfile(manifest_path):
        return None
    manifest = _read_json(manifest_path)
    if not isinstance(manifest, dict):
        return None
    errors = validate_manifest(manifest)
    if errors:
        print(f"[utility-scanner] invalid {manifest_path}: {errors}")
        return None

    mid = str(manifest["id"])
    schema_name = manifest.get("schema") or "form_schema.json"
    runtime_name = str(manifest.get("runtime") or "") or None
    schema_path = os.path.join(module_dir, schema_name)
    form_schema = None
    if os.path.isfile(schema_path):
        form_schema = _read_json(schema_path)
        errors = validate_form_schema(form_schema)
        if errors:
            print(f"[utility-scanner] invalid schema for '{mid}': {errors}")
            # A broken schema is a load failure: the utility must not serve a
            # half-rendered form. It is reported through the load-error (broken)
            # channel instead so the UI can point at the offending file.
            return None

    names = [schema_name]
    handler_names: List[str] = []
    handlers = manifest.get("handlers") or {}
    for key in ("python", "lua"):
        value = handlers.get(key)
        if isinstance(value, str) and value:
            handler_names.append(value)
    for candidate in [runtime_name] + handler_names:
        if candidate and candidate not in names:
            names.append(candidate)
    if os.path.isfile(os.path.join(module_dir, "requirements.txt")):
        names.append("requirements.txt")
    hashes = _file_hashes(module_dir, names)

    icon_rel = _sync_icons(module_dir, manifest.get("icon_file"))
    return {
        "manifest": manifest,
        "form_schema": form_schema,
        "hashes": hashes,
        "schema_path": schema_name,
        "runtime_path": runtime_name,
        "icon_rel": icon_rel,
        "runtime_ok": bool(runtime_name and os.path.isfile(os.path.join(module_dir, runtime_name))),
    }


def compile_cache() -> Dict[str, Any]:
    """Full scan + cache compile. Returns the cache document."""
    utilities: Dict[str, Any] = {}
    if not os.path.isdir(UTILITIES_DIR):
        print(f"[utility-scanner] utilities directory missing: {UTILITIES_DIR}")
    else:
        for name in sorted(os.listdir(UTILITIES_DIR)):
            module_dir = os.path.join(UTILITIES_DIR, name)
            if not os.path.isdir(module_dir):
                continue
            entry = scan_utility(module_dir)
            if entry:
                mid = str(entry["manifest"]["id"])
                entry["dir"] = os.path.normpath(module_dir)
                utilities[mid] = entry
    return {
        "version": CACHE_VERSION,
        "compiled_at": datetime.now().isoformat(timespec="seconds"),
        "utilities": utilities,
        "broken": {
            mid: entry for mid, entry in collect_broken().items() if mid not in utilities
        },
    }


def _write_json(path: str, payload: Any) -> None:
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, indent=2)
    except OSError:
        print(f"[utility-scanner] could not write {path}")


def _entry_changed(module_dir: str, cached: Dict[str, Any], computed: Dict[str, Any]) -> bool:
    for name, digest in computed.get("hashes", {}).items():
        if cached.get("hashes", {}).get(name) != digest:
            return True
    return False


def load_utilities(force_scan: bool = False) -> Dict[str, Any]:
    """Load utility listings, preferring the cache and validating SHA-256.

    Returns {"utilities": {id: entry}, "from_cache": bool, "recompiled": [ids],
             "broken": {id: error_entry}}.
    """
    cached: Dict[str, Any] = {}
    if not force_scan and os.path.isfile(CACHE_PATH):
        doc = _read_json(CACHE_PATH)
        if isinstance(doc, dict) and doc.get("version") == CACHE_VERSION:
            cached = doc.get("utilities") or {}

    recompiled: List[str] = []
    utilities: Dict[str, Any] = {}

    if os.path.isdir(UTILITIES_DIR):
        for name in sorted(os.listdir(UTILITIES_DIR)):
            module_dir = os.path.join(UTILITIES_DIR, name)
            if not os.path.isdir(module_dir):
                continue
            entry = scan_utility(module_dir)
            if not entry:
                continue
            mid = str(entry["manifest"]["id"])
            prior = cached.get(mid)
            if prior is not None and not _entry_changed(module_dir, prior, entry):
                # Fast Boot: nothing changed; reuse cached payloads.
                utilities[mid] = {
                    "manifest": prior.get("manifest") or entry["manifest"],
                    "form_schema": prior.get("form_schema"),
                    "hashes": prior.get("hashes") or entry["hashes"],
                    "schema_path": entry["schema_path"],
                    "runtime_path": entry["runtime_path"],
                    "icon_rel": prior.get("icon_rel") or entry["icon_rel"],
                    "runtime_ok": entry["runtime_ok"],
                    "dir": os.path.normpath(module_dir),
                }
                continue
            recompiled.append(mid)
            entry["dir"] = os.path.normpath(module_dir)
            utilities[mid] = entry
    else:
        print(f"[utility-scanner] utilities directory missing: {UTILITIES_DIR}")

    from_cache = not force_scan and not recompiled
    if recompiled or force_scan:
        doc = compile_cache()
        _write_json(CACHE_PATH, doc)
        _write_json(LOCK_PATH, {
            "updated_at": doc["compiled_at"],
            "recompiled": recompiled,
            "reason": "sha256_mismatch" if recompiled else "manual_scan",
        })
    return {"utilities": utilities, "from_cache": from_cache, "recompiled": recompiled,
            "broken": {mid: entry for mid, entry in collect_broken().items()
                       if mid not in utilities}}


def descriptor(entry: Dict[str, Any]) -> Dict[str, Any]:
    """React-facing utility descriptor (dashboard card + schema payload)."""
    manifest = entry.get("manifest") or {}
    return {
        "id": manifest.get("id"),
        "title": manifest.get("title") or manifest.get("id"),
        "description": manifest.get("description") or "",
        "icon": manifest.get("icon") or "",
        "icon_file": entry.get("icon_rel") or manifest.get("icon_file") or "",
        "badge": manifest.get("badge") or "",
        "tags": manifest.get("tags") or [],
        "version": manifest.get("version") or "",
        "form_schema": entry.get("form_schema"),
        "has_runtime": bool(entry.get("runtime_ok")),
        "runtime_file": entry.get("runtime_path"),
        "coming_soon": not entry.get("runtime_ok"),
    }


if __name__ == "__main__":
    sys.stdout.write(json.dumps(load_utilities(force_scan=True), default=str))